# Generated by Django 3.1.4 on 2022-09-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_auto_20220924_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
