# Generated by Django 3.1.4 on 2022-09-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_auto_20220926_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='skills',
        ),
    ]
