# Generated by Django 4.1.2 on 2022-10-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0006_remove_portfolio_image_about_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.URLField(null=True)),
                ('github', models.URLField(null=True)),
                ('linkedin', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
            ],
        ),
    ]
